Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GameDrop.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using GameDrop.Data;
using Microsoft.EntityFrameworkCore;
using GameDrop.Models;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameDrop.Services;
using System.Security.Claims;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using System.Net.Mail;
using System.Net;
using Microsoft.Extensions.Options;
using Org.BouncyCastle.Asn1.X509;

namespace GameDrop.Controllers
{
    public class OrderController : Controller
    {
        private readonly GameDropDBContext _db;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly EmailSettings _emailSettings;
        public OrderController(GameDropDBContext db, ShoppingCartService shoppingCartService, IOptions<EmailSettings> emailSettings)
        {
            _db = db;
            _shoppingCartService = shoppingCartService;
            _emailSettings = emailSettings.Value;
        }
        // GET: Order details from the shop page
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> ShoppingCart()
        {
            var cartItems = await GetShoppingCartItemsAsync();
            if (!cartItems.Any())
            {
                ViewBag.ErrorMessage = "Your shopping cart is empty.";
            }

            return View(cartItems);
        }

        private async Task AddShoppingCartItemsToOrderDetails(int orderId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cartItems = await _shoppingCartService.GetCartItemsByUserIdAsync(userId);

            foreach (var item in cartItems)
            {
                var orderDetail = new GameDrop_OrderDetails
                {
                    OrderId = orderId,
                    ProductId = item.Product.ProductId,
                    OrderProductName = item.Product.ProductName,
                    OrderQuantity = item.Quantity,
                    Total = item.Product.ProductPrice * item.Quantity
                };
                _db.OrderDetails.Add(orderDetail);
            }
            await _db.SaveChangesAsync();
        }

        private async Task<List<CartItem>> GetShoppingCartItemsAsync()
        {
            // Assuming you have a way to identify the current user or session
            // For example, using User.Identity.Name or a session ID
            var userId = User?.Identity?.Name;
            if (userId == null)
            {
                return new List<CartItem>();
            }
            return await _db.CartItems
                .Include(ci => ci.Product)
                .ToListAsync();
        }

        //GET: Order details view
        public async Task<IActionResult> OrderDetails()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cartItems = await _shoppingCartService.GetCartItemsByUserIdAsync(userId);

            var userAddresses = await _db.GameDrop_UserAddress
                .Where(ua => ua.UserId == userId)
                .ToListAsync();

            ViewBag.UserAddresses = userAddresses;
            return View(cartItems);
        }

        // Delete order details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrderDetail(int orderDetailId)
        {
            var orderDetail = await _db.OrderDetails.FindAsync(orderDetailId);
            if (orderDetail == null)
            {
                return NotFound();
            }

            _db.OrderDetails.Remove(orderDetail);
            await _db.SaveChangesAsync();

            return RedirectToAction("OrderDetails", new { id = orderDetail.OrderId });
        }

        // Proceed to payment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProceedToPayment(int selectedAddressId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var newOrder = new GameDrop_Order
            {
                OrderDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                OrderStatus = "Payment Pending",
                PaymentType = "Not Paid",
                UserAddressId = selectedAddressId,
                UserId = userId
            };

            _db.Orders.Add(newOrder);
            await _db.SaveChangesAsync();

            await AddShoppingCartItemsToOrderDetails(newOrder.OrderId);

            await _shoppingCartService.ClearCartAsync(userId);

            return RedirectToAction("Payment", new { id = newOrder.OrderId, orderDate = newOrder.OrderDate, orderStatus = newOrder.OrderStatus });
        }

        public IActionResult Payment(int id, string orderDate, string orderStatus)
        {
            // Implement your payment view logic here
            ViewBag.OrderId = id;
            ViewBag.OrderDate = orderDate;
            ViewBag.OrderStatus = orderStatus;
            ViewBag.TotalAmount = _db.OrderDetails.Where(od => od.OrderId == id).Sum(od => od.Total);

            return View();

        }
        // complete payment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CompletePayment(int orderId, string paymentMethod)
        {
            // Implement your payment completion logic here
            // For now, just mark the order as completed and redirect to a confirmation page

            var order = _db.Orders.Find(orderId);

            if (order == null)
            {
                return NotFound();
            }

            // Update the order status to Paid
            order.OrderStatus = "Paid";
            order.PaymentType = paymentMethod;

            _db.SaveChanges();

            return RedirectToAction("OrderSummary", new { id = orderId });
        }

        public async Task<IActionResult> OrderSummary(int id)
        {
            var orderDetails = await _db.OrderDetails
                .Where(od => od.OrderId == id)
                .Include(od => od.Product)
                .ToListAsync();

            if (!orderDetails.Any())
            {
                return NotFound();
            }

            var order = await _db.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }

            ViewBag.OrderId = id;
            ViewBag.OrderDate = order.OrderDate;
            ViewBag.OrderStatus = order.OrderStatus;
            ViewBag.TotalAmount = orderDetails.Sum(od => od.Total);
            return View(orderDetails);
        }

        public async Task<IActionResult> ManageOrder()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var orders = await _db.Orders
                .Where(o => o.UserId == userId)
                .ToListAsync();
            var orderDetails = await _db.OrderDetails
                .Where(od => orders.Select(o => o.OrderId).Contains(od.OrderId))
                .Include(od => od.Product)
                .ToListAsync();

            ViewBag.TotalOrders = orders.Count;
            ViewBag.TotalAmount = orderDetails.Sum(od => od.Total);

            return View(orders);
        }

        [HttpGet]
        public async Task<IActionResult> GenerateInvoice(int orderId)
        {
            var orderDetails = await _db.OrderDetails
                .Where(od => od.OrderId == orderId)
                .Include(od => od.Product)
                .ToListAsync();

            if (!orderDetails.Any())
            {
                return NotFound();
            }

            var order = await _db.Orders.FindAsync(orderId);
            if (order == null)
            {
                return NotFound();
            }

            var memoryStream = new MemoryStream();
            var document = new Document();
            var writer = PdfWriter.GetInstance(document, memoryStream);
            writer.CloseStream = false;
            document.Open();

            // Add content to the PDF
            document.Add(new Paragraph("Invoice"));
            document.Add(new Paragraph($"Order ID: {order.OrderId}"));
            document.Add(new Paragraph($"Order Date: {order.OrderDate}"));
            document.Add(new Paragraph($"Order Status: {order.OrderStatus}"));
            document.Add(new Paragraph(" "));

            var table = new PdfPTable(4);
            table.AddCell("Product Name");
            table.AddCell("Quantity");
            table.AddCell("Price");
            table.AddCell("Total");

            foreach (var detail in orderDetails)
            {
                table.AddCell(detail.OrderProductName);
                table.AddCell(detail.OrderQuantity.ToString());
                table.AddCell(detail.Product.ProductPrice.ToString("C"));
                table.AddCell(detail.Total.ToString("C"));
            }

            document.Add(table);
            document.Close();

            memoryStream.Position = 0;
            return File(memoryStream, "application/pdf", $"Invoice_{order.OrderId}.pdf");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendEmailWithAttachment(GameDrop_Order order, MemoryStream pdfStream, int orderId)
        {
            var memoryStream = new MemoryStream();
            await GenerateInvoice(orderId);

            var email = User.FindFirstValue(ClaimTypes.Email); // Get the email from the user's claims
            if (string.IsNullOrEmpty(email))
            {
                throw new InvalidOperationException("User email not found.");
            }

            var subject = "Your Invoice for OrderID {order.OrderId}";
            var body = $"Dear Customer,\n\nPlease find attached the invoice for your order {order.OrderId}.\n\nThank you for your purchase!";

            using (var message = new MailMessage())
            {

Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using GameDrop.Data;
using System.Linq;
using GameDrop.Services;
using iTextSharp.text;

namespace GameDrop.Controllers
{
    public class SearchController : Controller
    {
        private readonly GameDropDBContext _db;
        private readonly CategoryService _categoryService;
        private const int PageSize = 10;

        public SearchController(GameDropDBContext db, CategoryService categoryService)
        {
            _db = db;
            _categoryService = categoryService;
        }

        public IActionResult Index(string SearchItem, string sortOrder, decimal? minPrice, decimal? maxPrice, int? categoryId, int pageNumber = 1)
        {
            var products = _db.Products.AsQueryable();

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentSearch = SearchItem;
            ViewBag.MinPrice = minPrice;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.Categories = _categoryService.GetCategories();
            ViewBag.CategoryId = categoryId;

            if (minPrice.HasValue)
            {
                products = products.Where(p => p.ProductPrice >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                products = products.Where(p => p.ProductPrice <= maxPrice.Value);
            }

            if (categoryId.HasValue)
            {
                products = products.Where(p => p.CategoryId == categoryId.Value);
            }

            if (!string.IsNullOrEmpty(SearchItem))
            {
                products = products.Where(ProductSearch =>
                    ProductSearch.ProductId.ToString().Contains(SearchItem) ||
                    (ProductSearch.ProductName != null && ProductSearch.ProductName.Contains(SearchItem)) ||
                    (ProductSearch.ProductDescription != null && ProductSearch.ProductDescription.Contains(SearchItem))
                );
                ViewData["Title"] = "Search Results: " + SearchItem;
            }
            else
            {
                if (categoryId.HasValue)
                {
                    var category = _db.Categories.FirstOrDefault(c => c.CategoryId == categoryId.Value);
                    ViewData["Title"] = category != null ? category.CategoryName : "Search List";
                }
                else
                {
                    ViewData["Title"] = "All Products";
                }
            }

            products = sortOrder switch
            {
                "name" => products.OrderBy(p => p.ProductName),
                "name_desc" => products.OrderByDescending(p => p.ProductName),
                "price" => products.OrderBy(p => p.ProductPrice),
                "price_desc" => products.OrderByDescending(p => p.ProductPrice),
                _ => products.OrderBy(p => p.ProductName),
            };

            var totalItems = products.Count();
            var totalPages = (int)Math.Ceiling(totalItems / (double)PageSize);

            products = products.Skip((pageNumber - 1) * PageSize).Take(PageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.TotalPages = totalPages;

            return View("Index", products.ToList());
        }
    }
}

Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using GameDrop.Data;
using GameDrop.Models;
using Microsoft.EntityFrameworkCore;

namespace GameDrop.Controllers
{
    public class ShopController : Controller
    {
        private readonly GameDropDBContext _context;

        public ShopController(GameDropDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            int pageSize = 10;
            var products = await _context.Products
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            int totalProducts = await _context.Products.CountAsync();
            int totalPages = (int)Math.Ceiling(totalProducts / (double)pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.TotalPages = totalPages;

            return View(products);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using GameDrop.Areas.Identity.Data
@model dynamic

@inject SignInManager<GameDropUser> SignInManager
@inject UserManager<GameDropUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
    var userName = user?.UserName;
    var profileImageData = user?.ProfileImageData;
    var profileImageType = user?.ProfileImageType;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameDrop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameDrop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="~/js/site.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="col container-fluid d-flex flex-row gap-2">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="material-symbols-rounded">menu</span>
                </button>
                <a class="navbar-brand me-auto" style="width:fit-content;" asp-controller="Home" asp-action="Index">GameDrop</a>
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <button type="button" class="btn" style="border:none;" data-bs-dismiss="offcanvas">
                            <span class="material-symbols-rounded">close</span>
                        </button>
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">GameDrop</h5>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav nav-underline flex-grow-1 gap-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                    <span class="material-symbols-rounded">home</span> Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Shop" asp-action="Index">
                                    <span class="material-symbols-rounded">
                                        storefront
                                    </span> Shop
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col container-fluid navbar-expand d-flex flex-row">
                <ul class="navbar-nav flex-grow-1 gap-2 justify-content-end">
                    <li class="nav-item">
                        <form asp-controller="Search" asp-action="Index" class="d-lg-flex d-none">
                            <div class="search-bar">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search" name="SearchItem">
                                    <button class="btn btn-outline-secondary" type="submit">
                                        <span class="material-symbols-rounded">
                                            search
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <div class="d-lg-none justify-content-end">
                            <button class="btn justify-content-end" type="button" data-bs-toggle="collapse" data-bs-target="#searchCollapse" aria-expanded="false" aria-controls="searchCollapse">
                                <span class="material-symbols-rounded">
                                    search
                                </span>
                            </button>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="ShoppingCart" asp-action="Index" class="nav-link" role="button">
                            <span class="material-symbols-rounded">
                                shopping_cart
                            </span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <button class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @if (profileImageData != null && profileImageData.Length > 0)
                                {
                                    var base64 = Convert.ToBase64String(profileImageData);
                                    var imgSrc = $"data:{profileImageType};base64,{base64}";
                                    <img src="@imgSrc" alt="Profile Image" class="rounded-circle" style="width: 25px; height: 25px; object-fit: cover; overflow:hidden;" />
                                }
                                else
                                {
                                    <img src="/img/placeholder.jpg" alt="Placeholder Image" class="rounded-circle" style="width: 75px; overflow:hidden;" />
                                }
                                @UserManager.GetUserName(User)
                            </button>
                        }
                        else
                        {
                            <button class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                More
                            </button>
                        }
                        <ul class="dropdown-menu dropdown-menu-end">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li>
                                    <a class="dropdown-item" asp-controller="Order" asp-action="ManageOrder">
                                        <span class="material-symbols-rounded">
                                            list_alt
                                        </span> ManageOrder
                                    </a>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">
                                        <span class="material-symbols-rounded">
                                            manage_accounts
                                        </span> Manage Account
                                    </a>
                                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button id="logout" type="submit" class="dropdown-item">
                                            <span class="material-symbols-rounded">
                                                logout
                                            </span> Logout
                                        </button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">
                                        <span class="material-symbols-rounded">
                                            app_registration
                                        </span> Register
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Login">
                                        <span class="material-symbols-rounded">
                                            login
                                        </span> Login
                                    </a>
                                </li>
                            }
                            <li><hr class="dropdown-divider"></li>
                            <li><h6 class="dropdown-header">Quick Settings</h6></li>
                            <li>
                                <div class="dropdown-item">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="darkModeSwitch" checked>
                                        <label class="form-check-label" for="darkModeSwitch" id="darkModeSwitchTitle">Dark Mode</label>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="container-fluid d-lg-none collapse w-100">
                <ul class="navbar-nav d-lg-none collapse w-100" id="searchCollapse">
                    <form asp-controller="Search" asp-action="Index" class="w-100">
                        <div class="search-bar mt-2 mw-100">
                            <div class="input-group d-flex">
                                <input type="text" class="form-control w-auto" placeholder="Search..." aria-label="Search" name="SearchItem">
                                <button class="btn btn-outline-secondary" type="submit">
                                    <span class="material-symbols-rounded">
                                        search
                                    </span>
                                </button>
                            </div>
                        </div>
                    </form>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-break">
            &copy; 2024 - GameDrop - <a asp-area="" asp-controller="Home" asp-action="Credit">Credit</a> / <a asp-area="" asp-controller="Admin" asp-action="Index">Admin Dashboard</a>
        </div>
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const htmlElement = document.documentElement;
            const switchElement = document.getElementById('darkModeSwitch');

            // Set the default theme to dark if no setting is found in local storage
            const currentTheme = localStorage.getItem('bsTheme') || 'dark';
            htmlElement.setAttribute('data-bs-theme', currentTheme);
            switchElement.checked = currentTheme === 'dark';

            switchElement.addEventListener('change', function () {
                if (this.checked) {
                    htmlElement.setAttribute('data-bs-theme', 'dark');
                    localStorage.setItem('bsTheme', 'dark');
                    document.getElementById('darkModeSwitchTitle').textContent = 'Dark Mode';
                } else {
                    htmlElement.setAttribute('data-bs-theme', 'light');
                    localStorage.setItem('bsTheme', 'light');
                    document.getElementById('darkModeSwitchTitle').textContent = 'Light Mode';
                }
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>